{% set version = '1.0.0' %}
{% set name = "ggseabubble" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggseabubble
  version: {{ version }}

source:
  path: ../../../
build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base >=4.0.0
    - r-tidyverse >=2.0.0
    - r-ggtree >=3.8.0
    - r-patchwork >=1.1.3
    - r-scales >=1.3.0

  run:
    - r-base >=4.0.0
    - r-tidyverse >=2.0.0
    - r-ggtree >=3.8.0
    - r-patchwork >=1.1.3
    - r-scales >=1.3.0
    
test:
  commands:
    - $R -e "library(\"{{ name }}\")"           # [not win]
    - "\"%R%\" -e \"library(\"{{ name }}\")\""  # [win]

about:
  home: https://github.com/cnio-bu/ggseabubble
  license: GPL-3
  summary: ggseabubble creates publication-ready bubble heatmaps using ggplot2 and GSEA results.
  license_file:
    - LICENSE
