name: conda_build

on:
  push:
    branches: [master, development, CI]
  pull_request:
    branches:  [master, development, CI]


env:
  CACHE_NUMBER: 0

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/ggseabubble_builds

          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/ggseabubble_builds

    name: ${{ matrix.label }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: ggseabubble_builds
            conda-version: "23.5.2"
            use-mamba: true

      - name: Update ggseabubble environment
        run: |
          mamba update -n ggseabubble_builds -f helpers/mambabuild.yml
          conda config --append channels bioconda
      
      - name: Install ggseabubble package
        shell: bash -l {0}
        run: |
          conda activate ggseabubble_builds
          mamba install boa -y
          conda config --show channels
          mamba mambabuild ./.github/workflows/r-ggseabubble
          mamba install --use-local r-ggseabubble
      
      - name: Archive ggseabubble package for GNU/Linux
        uses: actions/upload-artifact@v3
        with:
          name: Linux_r-ggseabubble-v1.0.0
          path: /usr/share/miniconda3/envs/ggseabubble_builds/conda-bld/linux-64/r-ggseabubble-1.0.0-r43_0.tar.bz2
          
      - name: Archive ggseabubble package for macOS
        uses: actions/upload-artifact@v3
        with:
          name: macOS_r-ggseabubble-v1.0.0
          path: /Users/runner/miniconda3/envs/ggseabubble_builds/conda-bld/osx-64/r-ggseabubble-1.0.0-r43_0.tar.bz2